### ISSUE TITLE
exog and endog are not aligned

### ISSUE THREAD

**Issue by rhmills** [biocore/gneiss#176]
I'm trying to run the following commands

```
qiime gneiss ols-regression   --i-table composition.biom.qza \
                              --i-tree protein.tree.nwk.qza \
                              --m-metadata-file metadata_final.txt \
                              --p-formula "Weight+CRP+Calprotectin+Lactoferrin" \
                              --o-linear-model linear_protein_model.qza \
                              --verbose


qiime gneiss ols-summary --i-model linear_protein_model.qza \
                         --o-visualization linear_protein_model_summary.qzv
```
And I'm getting the following error in my dataset. 

```
Traceback (most recent call last):
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/q2cli-2017.2.0-py3.5.egg/q2cli/commands.py", line 217, in
 
__call__
    results = action(**arguments)
  File "<decorator-gen-123>", line 2, in ols_regression
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/qiime2-2017.2.0-py3.5.egg/qiime2/sdk/action.py", line 171, in callable_wrapper
    output_types, provenance)
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/qiime2-2017.2.0-py3.5.egg/qiime2/sdk/action.py", line 248, in _callable_executor_
    output_views = callable(**view_args)
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/gneiss-0.3.2-py3.5.egg/gneiss/regression/_regression.py", line 24, in ols_regression
    formula=formula)
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/gneiss-0.3.2-py3.5.egg/gneiss/regression/_ols.py", line 172, in ols
    submodels = _fit_ols(ilr_table, x)
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/gneiss-0.3.2-py3.5.egg/gneiss/regression/_ols.py", line 25, in _fit_ols
    return [smf.OLS(endog=y[b], exog=x, **kwargs) for b in y.columns]
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/gneiss-0.3.2-py3.5.egg/gneiss/regression/_ols.py", line 25, in <listcomp>
    return [smf.OLS(endog=y[b], exog=x, **kwargs) for b in y.columns]
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/regression/linear_model.py", line 631, in __init__
    hasconst=hasconst, **kwargs)
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/regression/linear_model.py", line 526, in __init__
    weights=weights, hasconst=hasconst, **kwargs)
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/regression/linear_model.py", line 95, in __init__
    super(RegressionModel, self).__init__(endog, exog, **kwargs)
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/base/model.py", line 212, in __init__
    super(LikelihoodModel, self).__init__(endog, exog, **kwargs)
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/base/model.py", line 63, in __init__
    **kwargs)
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/base/model.py", line 88, in _handle_data
    data = handle_data(endog, exog, missing, hasconst, **kwargs)
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/base/data.py", line 630, in handle_data
    **kwargs)
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/base/data.py", line 80, in __init__
    self._check_integrity()
  File "/home/rhmills/miniconda2/envs/gneiss_env/lib/python3.5/site-packages/statsmodels/base/data.py", line 495, in _check_integrity
    raise ValueError("The indices for endog and exog are not aligned")
ValueError: The indices for endog and exog are not aligned
```
Any idea what is going on!?!?!

**Comment by mortonjt** [comment]
This has been addressed in #186 when we removed the dependency on statsmodels.  I'm going to close this - but let me know if this problem pops up again
